apiVersion: v1
kind: ConfigMap
metadata:
  name: simulator-conf
data:
  env: |
    KafkaBootstrapServers={{ CLUSTER_URL_SERVER }}
    KafkaConsumerGroupId=simulator
    KafkaReadTopic=route.new-direction
    KafkaProduceTopic=route.new-position
    security.protocol=SASL_SSL
    sasl.mechanisms=PLAIN
    sasl.username={{ CLUSTER_API_KEY }}
    sasl.password={{ CLUSTER_API_SECRET }}
